name: Config check

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    # branches:
    # branches-ignore:
    #  - master
    #  - alpha

jobs:
  check:
    name: Config check
    uses: tksst/github-actions-workflows/.github/workflows/nodejs-pnpm.yml@f49ab363c3ce9708e9d067dc81d2c253b9c6ac31
    with:
      build: false
      test: false
      os: '["ubuntu-latest"]'
      node-versions: "[18]"
