name: Config check

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  check:
    name: Check
    runs-on: ubuntu-22.04
    steps:
      - name: Check whether it can skip
        id: check-skippable
        continue-on-error: true
        uses: fkirc/skip-duplicate-actions@12aca0a884f6137d619d6a8a09fcc3406ced5281 # v5.3.0

      - name: set up the project
        if: steps.check-skippable.outputs.should_skip != 'true'
        uses: tksst/github-actions-workflows/actions/setup-pnpm-project@269a893f6432649083afd1c3c6350793e8c00e4b

      - if: steps.check-skippable.outputs.should_skip != 'true'
        run: pnpm lint
