name: Config check

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  check:
    name: Check
    runs-on: ubuntu-22.04
    steps:
      - name: Check whether it can skip
        id: check-skippable
        continue-on-error: true
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1

      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@94c3c3d9567a0205de6da68a76c428ce4e769af1 # v2.0.0
        if: steps.check-skippable.outputs.should_skip != 'true'
        with:
          # Set to true to publish the results as comment to the PR (applicable if workflow run is triggered by PR).
          comment_on_pr: false

      - uses: Kesin11/actions-timeline@40b912d44677e158feec8015d092b5428f9c8247 # v2.0.2
        if: steps.check-skippable.outputs.should_skip != 'true'

      - name: Checkout the source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        if: steps.check-skippable.outputs.should_skip != 'true'
        with:
          show-progress: false
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        if: steps.check-skippable.outputs.should_skip != 'true'
        with:
          standalone: true

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        if: steps.check-skippable.outputs.should_skip != 'true'
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        if: steps.check-skippable.outputs.should_skip != 'true'

      - if: steps.check-skippable.outputs.should_skip != 'true'
        run: pnpm lint
