name: Config check

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  check:
    name: Check
    runs-on: ubuntu-24.04
    steps:
      - name: Check whether it can skip
        id: check-skippable
        continue-on-error: true
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1

      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@94c3c3d9567a0205de6da68a76c428ce4e769af1 # v2.0.0
        if: steps.check-skippable.outputs.should_skip != 'true'
        with:
          # Set to true to publish the results as comment to the PR (applicable if workflow run is triggered by PR).
          comment_on_pr: false

      - uses: Kesin11/actions-timeline@427ee2cf860166e404d0d69b4f2b24012bb7af4f # v2.2.3
        if: steps.check-skippable.outputs.should_skip != 'true'

      - name: Checkout the source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        if: steps.check-skippable.outputs.should_skip != 'true'
        with:
          show-progress: false
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        if: steps.check-skippable.outputs.should_skip != 'true'
        with:
          standalone: true

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        if: steps.check-skippable.outputs.should_skip != 'true'
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        if: steps.check-skippable.outputs.should_skip != 'true'

      - if: steps.check-skippable.outputs.should_skip != 'true'
        run: pnpm lint
