name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: setup-node
        uses: actions/setup-node@348e00800850ca70958af8888ebdb3cce7cbcddc
        with:
          node-version: 18
          cache: npm

      - name: Enable corepack
        run: corepack enable npm

      - run: npm ci

      - run: npm run check
